name: Deployment

on:
  pull_request:
  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        description: Cloud
        options: 
        - hcloud
        - aws
        - azure
      app:
        type: choice
        description: Application
        options:
        - ansible-azuracast
        - ansible-vh-server
        - ansible-cs-server

jobs:
  terraform:
    uses: clickopss/workflow-terraform/.github/workflows/workflow.yml@main
    with:
      tf_cloud: ${{ github.event.inputs.cloud }}
    secrets: inherit


  ansible:
    needs: terraform
    uses: clickopss/workflow-ansible/.github/workflows/workflow.yml@main
    with:
      ipv4: ${{ needs.terraform.outputs.ipv4 }}
      ansible_deployment: ${{ github.event.inputs.app }}
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
